import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,Link,Route,Routes,useLocation,useNavigate,useParams} from 'react-router-dom';
import {ArrowUpRight,Copy,Menu,X} from 'lucide-react';
import './styles.css';

type Project={id:number;title:string;category:string;year:string;description:string;slug:string;client:string;role:string;services:string;tools:string;art:string};
const projects:Project[]=[
{id:1,title:'Black Signal',category:'Art Direction',year:'2026',description:'A visual identity exploring contrast, movement and digital materiality through a monochrome system.',slug:'black-signal',client:'Independent',role:'Creative Direction',services:'Art Direction / Identity / Digital',tools:'Figma / Photoshop / After Effects',art:'a1'},
{id:2,title:'Afterimage',category:'Digital Experience',year:'2025',description:'An experimental interface for an imagined contemporary art archive.',slug:'afterimage',client:'Studio Project',role:'Digital Designer',services:'UX/UI / Interaction / Prototyping',tools:'Figma / React / Motion',art:'a2'},
{id:3,title:'Object 03',category:'3D / Visual',year:'2025',description:'A study of form, shadow and synthetic materials translated into a tactile poster series.',slug:'object-03',client:'Experimental',role:'Visual Designer',services:'3D Art / Posters / Motion',tools:'Blender / C4D / Photoshop',art:'a3'},
{id:4,title:'Nocturne',category:'Brand Identity',year:'2024',description:'A restrained identity system built around typography, rhythm and negative space.',slug:'nocturne',client:'Nocturne Studio',role:'Brand Designer',services:'Branding / Art Direction / Typography',tools:'Illustrator / InDesign / Figma',art:'a4'},
{id:5,title:'Future Relics',category:'Editorial',year:'2024',description:'An editorial experiment imagining artifacts from a near-future design culture.',slug:'future-relics',client:'Self-Initiated',role:'Art Director',services:'Editorial / Art Direction / Image Making',tools:'InDesign / Photoshop / Blender',art:'a5'},
{id:6,title:'Static / Motion',category:'Campaign',year:'2023',description:'A campaign language where still graphics and motion frames share one modular visual system.',slug:'static-motion',client:'Culture Lab',role:'Visual Director',services:'Campaign / Motion / Digital',tools:'After Effects / Figma / Photoshop',art:'a6'}];
const getProject=(slug:string)=>projects.find(p=>p.slug===slug);

function Nav(){const[open,setOpen]=useState(false);const loc=useLocation();const go=(id:string)=>{setOpen(false);if(loc.pathname!=='/'){window.location.href='/#'+id;return;}document.getElementById(id)?.scrollIntoView({behavior:'smooth'});};return <header className={'nav '+(open?'open':'')}><Link className="brand" to="/">NOIR<span>®</span></Link><button className="menu" aria-label="Toggle navigation" onClick={()=>setOpen(!open)}>{open?<X size={19}/>:<Menu size={19}/>}</button><nav><button onClick={()=>go('work')}>WORK</button><button onClick={()=>go('about')}>ABOUT</button><button onClick={()=>go('archive')}>ARCHIVE</button><button onClick={()=>go('contact')}>CONTACT</button></nav><span className="status">AVAILABLE / 2026</span></header>}
function Cursor(){const[p,setP]=useState({x:-100,y:-100});const[a,setA]=useState(false);const[l,setL]=useState('');useEffect(()=>{const move=(e:MouseEvent)=>setP({x:e.clientX,y:e.clientY});const over=(e:MouseEvent)=>{const t=(e.target as HTMLElement).closest('[data-cursor]');if(t){setA(true);setL(t.getAttribute('data-cursor')||'')}};const out=(e:MouseEvent)=>{if((e.target as HTMLElement).closest('[data-cursor]')){setA(false);setL('')}};addEventListener('mousemove',move);document.addEventListener('mouseover',over);document.addEventListener('mouseout',out);return()=>{removeEventListener('mousemove',move);document.removeEventListener('mouseover',over);document.removeEventListener('mouseout',out)}} ,[]);return <div className={'cursor '+(a?'active':'')} style={{transform:`translate3d(${p.x}px,${p.y}px,0)`}}>{l}</div>}
function Art({type='a1',large=false}:{type?:string;large?:boolean}){return <div className={'art '+type+(large?' large':'')}><i className="grid"/><i className="orbit one"/><i className="orbit two"/><i className="core"/></div>}
function Card({p,i}:{p:Project;i:number}){return <Link to={'/project/'+p.slug} className={'card c'+(i+1)} data-cursor="VIEW"><Art type={p.art}/><div className="card-meta"><small>0{p.id}</small><div><h3>{p.title}</h3><p>{p.category} / {p.year}</p></div><ArrowUpRight size={18}/></div></Link>}
function Home(){return <><Cursor/><Nav/><main><section className="hero"><div className="hero-top"><span>INDEPENDENT DESIGNER</span><span>01—06 / SELECTED WORK</span></div><h1><span>MAKE</span><span>IT</span><span>MATTER<span>.</span></span></h1><div className="hero-bottom"><p>Visual systems, digital experiences and experimental objects<br/>made between design and culture.</p><small>SCROLL TO EXPLORE ↓</small></div></section><section id="work" className="work shell"><div className="head"><div><label>SELECTED WORK</label><h2>THE<br/>COLLECTION<span>.</span></h2></div><p>Six visual experiments across identity, digital, editorial and image-making.</p></div><div className="stage">{projects.map((p,i)=><Card key={p.id} p={p} i={i}/>)}</div></section><About/><Archive/><Contact/><Footer/></main></>}
function About(){return <section id="about" className="about shell"><label>02 / ABOUT</label><div className="about-grid"><h2>DESIGN SHOULD<br/>LEAVE A<br/><em>TRACE.</em></h2><div className="copy"><p className="lead">I am an independent designer focused on visual identity, digital experiences and art direction.</p><p>My practice sits between graphic design, technology and visual culture. I like systems that are precise but never sterile, expressive without becoming noisy, and simple enough to remember.</p><p>Available for selected freelance collaborations, creative direction and digital design projects.</p></div></div><div className="facts"><div><span>BASED</span><b>YOUR CITY / WORLDWIDE</b></div><div><span>FOCUS</span><b>IDENTITY / DIGITAL / ART DIRECTION</b></div><div><span>TOOLS</span><b>FIGMA / ADOBE / BLENDER / CODE</b></div><div><span>STATUS</span><b>OPEN FOR SELECTED PROJECTS</b></div></div></section>}
function Archive(){const[h,setH]=useState<Project|null>(null);return <section id="archive" className="archive shell"><label>03 / ARCHIVE</label><h2>OLDER<br/>WORK<span>.</span></h2><div className="rows">{[...projects].reverse().map(p=><Link data-cursor="VIEW" onMouseEnter={()=>setH(p)} onMouseLeave={()=>setH(null)} key={p.id} to={'/project/'+p.slug}><span>{p.year}</span><b>{p.title}</b><span>{p.category}</span><ArrowUpRight size={16}/></Link>)}</div>{h&&<div className="preview"><Art type={h.art}/></div>}</section>}
function Contact(){const[c,setC]=useState(false);const email='hello@noir.studio';const copy=async()=>{await navigator.clipboard?.writeText(email);setC(true);setTimeout(()=>setC(false),1600)};return <section id="contact" className="contact shell"><label>04 / CONTACT</label><h2>LET'S MAKE<br/>SOMETHING<span>.</span></h2><div className="contact-bottom"><button onClick={copy} data-cursor="COPY">{c?'COPIED':email}<Copy size={17}/></button><div><a href="#">INSTAGRAM</a><a href="#">BEHANCE</a><a href="#">LINKEDIN</a></div></div></section>}
function Footer(){return <footer className="footer shell"><span>© {new Date().getFullYear()} NOIR®</span><span>DESIGN / ART DIRECTION / DIGITAL</span><button onClick={()=>scrollTo({top:0,behavior:'smooth'})}>BACK TO TOP ↑</button><span>{new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</span></footer>}
function Project(){const{slug}=useParams();const nav=useNavigate();const p=getProject(slug||'');if(!p)return <><Nav/><div className="notfound"><h1>NOT FOUND<span>.</span></h1><button onClick={()=>nav('/')}>BACK HOME</button></div></>;const next=projects[p.id%projects.length];return <><Cursor/><Nav/><main className="case"><section className="case-head shell"><button onClick={()=>nav(-1)}>← BACK TO WORK</button><label>PROJECT 0{p.id} / {p.year}</label><h1>{p.title}<span>.</span></h1><p>{p.description}</p><Art type={p.art} large/></section><section className="case-info shell"><div><span>CLIENT</span><b>{p.client}</b></div><div><span>ROLE</span><b>{p.role}</b></div><div><span>SERVICES</span><b>{p.services}</b></div><div><span>TOOLS</span><b>{p.tools}</b></div></section><section className="story shell"><p className="statement">A visual study of contrast, material, rhythm and interaction.</p><div className="story-grid"><Art type={p.art}/><Art type={p.art}/></div><p className="bodycopy">The project was developed as a flexible visual system: one language that could move between static compositions, interfaces and motion. The result is deliberately reduced, allowing scale, typography and image-making to do most of the work.</p></section><section className="next shell"><label>NEXT PROJECT</label><Link data-cursor="VIEW" to={'/project/'+next.slug}>{next.title}<ArrowUpRight size={35}/></Link></section><Footer/></main></>}
function App(){return <Routes><Route path="/" element={<Home/>}/><Route path="/project/:slug" element={<Project/>}/></Routes>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><BrowserRouter><App/></BrowserRouter></React.StrictMode>);
